[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "jitasm"
version = "0.2.0"
description = "An JIT x86-64 Assembler"
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.7"
dependencies = []

[[tool.setuptools.ext-modules]]
name = "jitasm.utils"
sources = ["src/jitasm/utils.c"]
extra-compile-args = ["-O3"]

[project.urls]
Homepage = "https://github.com/mistivia/jitasm-py"
Repository = "https://github.com/mistivia/jitasm-py"
Issues = "https://github.com/mistivia/jitasm/issues"
